"""empty message

Revision ID: 2c3d88cbf0a6
Revises: 5c2822836ed0
Create Date: 2024-11-01 22:41:00.625779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3d88cbf0a6'
down_revision = '5c2822836ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_type', sa.String(), server_default='tests', nullable=True))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('text')
        batch_op.drop_column('check_type')

    # ### end Alembic commands ###
