"""empty message

Revision ID: 3d9f899fd4f8
Revises: f5bb02e365c8
Create Date: 2025-12-22 21:38:20.335118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9f899fd4f8'
down_revision = 'f5bb02e365c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_ai_warning', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('ai_warning_reasons', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gpt_llm_probability', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_column('gpt_llm_probability')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('ai_warning_reasons')
        batch_op.drop_column('has_ai_warning')

    # ### end Alembic commands ###
