"""empty message

Revision ID: 4033553b5e45
Revises: 8e39446b4bb8
Create Date: 2024-11-07 21:05:34.357673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4033553b5e45'
down_revision = '8e39446b4bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_critical_similarity_warning', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_column('has_critical_similarity_warning')

    # ### end Alembic commands ###
