"""Add available_without_auth field to Code

Revision ID: 437fbd10b406
Revises: 3d9f899fd4f8
Create Date: 2026-01-23 16:51:33.023513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437fbd10b406'
down_revision = '3d9f899fd4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_without_auth', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_column('available_without_auth')

    # ### end Alembic commands ###
