"""empty message

Revision ID: 718a865afdf9
Revises: 8949571042ba
Create Date: 2024-10-27 16:14:18.787671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718a865afdf9'
down_revision = '8949571042ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('testing_framework', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_state', sa.String(length=255), server_default='not checked', nullable=True))
        batch_op.add_column(sa.Column('check_result', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('check_comments', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('check_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('checked_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'tasks', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('checked_at')
        batch_op.drop_column('check_points')
        batch_op.drop_column('check_comments')
        batch_op.drop_column('check_result')
        batch_op.drop_column('check_state')
        batch_op.drop_column('task_id')

    op.drop_table('tasks')
    # ### end Alembic commands ###
