"""empty message

Revision ID: 75563edc3c59
Revises: 718a865afdf9
Create Date: 2024-10-27 16:19:02.175218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75563edc3c59'
down_revision = '718a865afdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('lang')

    # ### end Alembic commands ###
