"""empty message

Revision ID: 8e39446b4bb8
Revises: 2c3d88cbf0a6
Create Date: 2024-11-02 12:43:52.003078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e39446b4bb8'
down_revision = '2c3d88cbf0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_similarity_warning', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('checked', new_column_name='similarity_checked', existing_type=sa.Boolean(),
                              existing_server_default='false', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_column('has_similarity_warning')
        batch_op.drop_column('similarity_checked')

    # ### end Alembic commands ###
