"""empty message

Revision ID: d58d8479fe79
Revises: 
Create Date: 2024-10-26 21:46:43.935594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58d8479fe79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similarities',
    sa.Column('code_id', sa.String(), nullable=False),
    sa.Column('code_id2', sa.String(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_id2'], ['codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_id', 'code_id2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarities')
    op.drop_table('codes')
    # ### end Alembic commands ###
