"""empty message

Revision ID: f5bb02e365c8
Revises: c306504c584b
Create Date: 2025-09-25 19:59:46.048359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bb02e365c8'
down_revision = 'c306504c584b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed_by_teacher', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codes', schema=None) as batch_op:
        batch_op.drop_column('viewed_by_teacher')

    # ### end Alembic commands ###
